"""Fit only the supplied seventh costal cartilage surface, never unused OBJ vertices.
Run with an explicit offline atlas directory. BodyParts3D / DBCLS, CC BY 4.0.
"""
import argparse
import hashlib
import json
from pathlib import Path
import numpy as np

parser = argparse.ArgumentParser()
parser.add_argument('atlas', type=Path)
args = parser.parse_args()
root = Path(__file__).resolve().parents[2]
origin = np.array([-.3152345, -205.92635, 1164.5735])
source = []
meshes = []
for name in ['FJ3345', 'FJ3255']:
    path = args.atlas / (name + '.obj')
    vertices, faces = [], []
    for line in path.read_text().splitlines():
        if line.startswith('v '):
            vertices.append(list(map(float, line.split()[1:4])))
        if line.startswith('f '):
            faces.append([int(x.split('/')[0])-1 for x in line.split()[1:]])
    v = np.array(vertices) - origin
    v[:, 1] = 85.25 - v[:, 1]
    v[:, 0] = -np.abs(v[:, 0])
    used = sorted({i for f in faces for i in f})
    source.append({'element': name, 'sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
                   'usedVertices': len(used), 'discardedUnusedVertices': len(v)-len(used)})
    meshes.append((v, faces, used))
# Preserve source right/left symmetry as an explicit averaging approximation.
x0 = max(v[used, 0].min() for v, _, used in meshes) + .5
x1 = min(v[used, 0].max() for v, _, used in meshes) - .5
xs = np.linspace(x0, x1, 16)
rows = []
for x in xs:
    sides = []
    for v, faces, _ in meshes:
        hits = []
        for face in faces:
            for a, b in zip(face, face[1:] + face[:1]):
                va, vb = v[a], v[b]
                if (va[0] <= x < vb[0]) or (vb[0] <= x < va[0]):
                    hits.append(va[1:] + (vb[1:]-va[1:]) * ((x-va[0])/(vb[0]-va[0])))
        h = np.array(hits)
        lo, hi = h.min(0), h.max(0)
        sides.append(np.r_[(lo+hi)/2, (hi-lo)/2])
    rows.append(np.mean(sides, axis=0).tolist())
rows = np.round(rows, 5).tolist()
def distance(p):
    z = np.clip((p[0]-x0)/(x1-x0)*15, 0, 15)
    i = min(14, int(z))
    a = np.array(rows[i]); b = np.array(rows[i+1]); q = a+(b-a)*(z-i)
    dy, dz = p[1]-q[0], p[2]-q[1]
    return max((np.hypot(dy/q[2], dz/q[3])-1)*min(q[2], q[3]), x0-p[0], p[0]-x1)
residuals = [abs(distance(p)) for v, _, used in meshes for p in v[used]]
report = {'license': 'BodyParts3D, © DBCLS, CC BY 4.0', 'source': source,
          'registration': {'sourceOriginLpsMm': origin.tolist(), 'targetXiphoidLasMm': [0,85.25,0]},
          'method': '16 original triangle-plane intersections; bounding ellipses in Y/Z; averaged reflected right and left; linear interpolation; closed source X endpoints',
          'scope': 'seventh cartilage only; no inferred cartilage for pairs 5,6,8,9,10',
          'x0': float(x0), 'x1': float(x1), 'rows': rows,
          'surfaceResidualMm': {'rms': float(np.sqrt(np.mean(np.square(residuals)))), 'p95': float(np.percentile(residuals,95)), 'max': float(max(residuals))},
          'clinicalValidation': False}
(root/'docs/anatomy/reference-cartilage-source.json').write_text(json.dumps(report, indent=2)+'\n')
out = '/** Generated by reference-cartilage.py from source triangle intersections; CC BY 4.0 DBCLS. */\n'
out += f'export const CARTILAGE_X0 = {x0:.8f};\nexport const CARTILAGE_X1 = {x1:.8f};\n'
out += 'export const CARTILAGE_ROWS = [\n' + ''.join('  '+json.dumps(row)+',\n' for row in rows) + '] as const;\n'
(root/'src/anatomy/referenceCartilageData.ts').write_text(out)
print(json.dumps(report['surfaceResidualMm']))
