/** Lossless transport dictionary. Decoding happens once while shader modules initialize. */
export const GLSL_WORDS = [
  'float',
  'return',
  'vec3',
  'uniform',
  'vec2',
  'vec4',
  'const',
  'normalize',
  'length',
  'texture',
  'clamp',
  'smoothstep',
  'sampler2D',
  'precision',
  'highp',
  'inversesqrt',
  'tissue',
  'define',
  'texelFetch',
  'int',
  'gl_FragCoord',
  'referenceCartilage',
  'min',
  'ivec2',
  'continue',
  'max',
  'include',
  'material',
  'endif',
  'ifdef',
  'reflectedLight',
  'defined',
  'varying',
  'roughness',
  'direction',
  'NUM_POINT_LIGHT_SHADOWS',
  'texture2D',
  'normal',
  'shadowIntensity',
  'color',
  'clipping_planes_pars_fragment',
  'specularColor',
  'NUM_DIR_LIGHT_SHADOWS',
  'clipping_planes_pars_vertex',
  'vViewPosition',
  'logdepthbuf_pars_fragment',
  'NUM_SUN_LIGHT_SHADOWS',
  'clipping_planes_fragment',
  'NUM_SPOT_LIGHT_SHADOWS',
  'tonemapping_fragment',
  'morphtarget_pars_vertex',
  'logdepthbuf_pars_vertex',
] as const;
export const GLSL_MARKERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
export function unpackGlsl(s: string): string {
  return s.replace(/@([A-Za-z])/g, (_, c: string) => GLSL_WORDS[GLSL_MARKERS.indexOf(c)] ?? `@${c}`);
}
